# Generated by Django 3.2.6 on 2022-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price_uzs', models.IntegerField(default=0, verbose_name='Цена в сумах')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Цена в долларах')),
                ('rooms', models.IntegerField(default=0, verbose_name='Кол-во комнат')),
                ('square', models.IntegerField(default=0, verbose_name='Площадь')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Этаж дома')),
                ('floor', models.IntegerField(default=0, verbose_name='Этажность')),
                ('plan', models.BooleanField(default=False, verbose_name='Планировка')),
                ('bathroom', models.BooleanField(default=False, verbose_name='Санузел')),
                ('furniture', models.BooleanField(default=False, verbose_name='Мебилирован')),
                ('ceiling', models.IntegerField(default=0, verbose_name='Высота потолка')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
            },
        ),
    ]
