# Generated by Django 3.2.6 on 2022-03-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_repaoir_flat_repair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='repair',
        ),
        migrations.AddField(
            model_name='flat',
            name='repaiir',
            field=models.CharField(choices=[('Variant3', 'Variant2'), ('Variant4', 'Variant3')], max_length=300, null=True, verbose_name='Ремонт'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='building_type',
            field=models.CharField(choices=[('Variant1', 'Variant1'), ('Variant2', 'Variant2')], max_length=300, null=True, verbose_name='Тип строения'),
        ),
    ]
