# Generated by Django 3.2.6 on 2022-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220330_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='building_type',
            field=models.CharField(choices=[('V1', 'Variant1'), ('V2', 'Variant2')], max_length=300, null=True, verbose_name='Тип строения'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='repaiir',
            field=models.CharField(choices=[('V1', 'Variant1'), ('V2', 'Variant2')], max_length=300, null=True, verbose_name='Ремонт'),
        ),
    ]
