# Generated by Django 3.2.6 on 2022-03-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220330_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price_uzs', models.IntegerField(default=0, verbose_name='Цена в сумах')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Цена в долларах')),
                ('rooms', models.IntegerField(default=0, verbose_name='Кол-во комнат')),
                ('square', models.IntegerField(default=0, verbose_name='Площадь')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Этаж дома')),
                ('floor', models.IntegerField(default=0, verbose_name='Этажность')),
                ('plan', models.BooleanField(default=False, verbose_name='Планировка')),
                ('bathroom', models.BooleanField(default=False, verbose_name='Санузел')),
                ('ceiling', models.IntegerField(default=0, verbose_name='Высота потолка')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('availibility', models.BooleanField(default=False, verbose_name='Availibility')),
                ('parking', models.BooleanField(default=False, verbose_name='Парковка')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price_uzs', models.IntegerField(default=0, verbose_name='Цена в сумах')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Цена в долларах')),
                ('rooms', models.IntegerField(default=0, verbose_name='Кол-во комнат')),
                ('square', models.IntegerField(default=0, verbose_name='Площадь')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Этаж дома')),
                ('plan', models.BooleanField(default=False, verbose_name='Планировка')),
                ('bathroom', models.BooleanField(default=False, verbose_name='Санузел')),
                ('ceiling', models.IntegerField(default=0, verbose_name='Высота потолка')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('furniture', models.BooleanField(default=False, verbose_name='Мебилирован')),
                ('total_square', models.IntegerField(default=0, verbose_name='Общая Площадь')),
                ('house_square', models.IntegerField(default=0, verbose_name='Жилая Площадь')),
                ('electricity', models.BooleanField(default=False, verbose_name='Электричество')),
                ('gas', models.BooleanField(default=False, verbose_name='Газ')),
                ('heating', models.BooleanField(default=False, verbose_name='Отопление')),
                ('water', models.BooleanField(default=False, verbose_name='Вода')),
                ('sewerage', models.BooleanField(default=False, verbose_name='Канализация')),
                ('repair', models.BooleanField(default=False, verbose_name='Ремонт')),
                ('building_type', models.CharField(choices=[('V1', 'Variant1'), ('V2', 'Variant2')], max_length=300, null=True, verbose_name='Ремонт')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price_uzs', models.IntegerField(default=0, verbose_name='Цена в сумах')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Цена в долларах')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('square', models.IntegerField(default=0, verbose_name='Площадь')),
                ('availibility', models.BooleanField(default=False, verbose_name='Availibility')),
            ],
        ),
        migrations.CreateModel(
            name='NewFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Загаловок')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price_uzs', models.IntegerField(default=0, verbose_name='Цена в сумах')),
                ('price_usd', models.IntegerField(default=0, verbose_name='Цена в долларах')),
                ('rooms', models.IntegerField(default=0, verbose_name='Кол-во комнат')),
                ('square', models.IntegerField(default=0, verbose_name='Площадь')),
                ('floor_number', models.IntegerField(default=0, verbose_name='Этаж дома')),
                ('floor', models.IntegerField(default=0, verbose_name='Этажность')),
                ('plan', models.BooleanField(default=False, verbose_name='Планировка')),
                ('bathroom', models.BooleanField(default=False, verbose_name='Санузел')),
                ('ceiling', models.IntegerField(default=0, verbose_name='Высота потолка')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
        ),
    ]
