# Generated by Django 3.2.6 on 2022-04-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_commercial_home_land_newflat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='building_type',
            field=models.CharField(choices=[('V1', 'Панельная'), ('V2', 'Кирпичная'), ('V2', 'Древесная')], max_length=300, null=True, verbose_name='Тип строения'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='repaiir',
            field=models.CharField(choices=[('V1', 'Евроремонт'), ('V2', 'Средний'), ('V2', 'Старый'), ('V2', 'Требует ремонта'), ('V2', 'Коробка')], max_length=300, null=True, verbose_name='Ремонт'),
        ),
    ]
