# Generated by Django 3.2.6 on 2022-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220414_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='building_type',
            field=models.CharField(choices=[('V1', 'Панельная'), ('V2', 'Кирпичная'), ('V3', 'Древесная')], max_length=300, null=True, verbose_name='Тип строения'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.CharField(choices=[('V1', 'Раздельная'), ('V2', 'Смежная'), ('V3', 'Смежно-раздельная')], max_length=300, null=True, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='repaiir',
            field=models.CharField(choices=[('V1', 'Евроремонт'), ('V2', 'Средний'), ('V3', 'Старый'), ('V4', 'Требует ремонта'), ('V5', 'Коробка')], max_length=300, null=True, verbose_name='Ремонт'),
        ),
    ]
