# Generated by Django 3.2.6 on 2022-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220414_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='price_uzs',
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.CharField(choices=[('V1', 'Раздельная'), ('V2', 'Смежная'), ('V3', 'Раздельно-смежная')], max_length=300, null=True, verbose_name='Планировка'),
        ),
    ]
